# Generated by Django 2.2.6 on 2019-11-02 10:46

from django.db import migrations, models
import modelcluster.contrib.taggit
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The body is additional content for larger devices'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='link',
            field=models.URLField(blank=True, help_text='Link to the original content.'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the quote. Useful for drafts and moderators. Not published.'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='reference',
            field=models.CharField(blank=True, help_text='If source is not link (like paper or archives)', max_length=250),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='source',
            field=models.CharField(blank=True, help_text='Original author or source. If website or article. Use link field but only the domain name here! Seek approval of the owner before publishing', max_length=120),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='summary',
            field=models.CharField(help_text='Mobile quote! Keep this short and effective', max_length=180),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='Tags to mark the content. ie: energy, diet, household...', through='greenhabits.GreenHabitTagPage', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
