# Generated by Django 2.2.6 on 2019-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0002_auto_20191102_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='source',
            field=models.CharField(default='', help_text='Original author or source. If website or article. Use link field but only the domain name here! Seek approval of the owner before publishing', max_length=120),
        ),
    ]
