# Generated by Django 2.2.6 on 2020-04-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0009_auto_20200418_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogTagPage',
        ),
    ]
