# Generated by Django 2.2.6 on 2020-04-18 03:38

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('greenhabits', '0010_auto_20200418_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageindex',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='header',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='importance',
            field=models.CharField(choices=[('law', 'Law'), ('essential', 'Essential'), ('habit', 'Habit')], default='habit', max_length=20),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the quote. Useful for drafts and moderators. Not published.'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='source',
            field=models.CharField(default='', help_text='Original author or source. If website or article. Use link field but only the domain name here! Seek approval of the owner before publishing', max_length=120),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='suggestion',
            field=models.CharField(help_text='Mobile quote! Keep this short and effective', max_length=180),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='Tags to mark the content. ie: energy, diet, household...', through='greenhabits.GreenHabitTagPage', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='BlogPageIndex',
        ),
    ]
