# Generated by Django 2.2.6 on 2020-04-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('greenhabits', '0012_auto_20200418_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogtagpage',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='blogtagpage',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='BlogPageIndex',
        ),
        migrations.DeleteModel(
            name='BlogTagPage',
        ),
    ]
