# Generated by Django 2.2.6 on 2020-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0015_auto_20200418_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhabitpage',
            name='suggestion',
        ),
    ]
