# Generated by Django 2.2.5 on 2021-02-23 02:22

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0016_remove_greenhabitpage_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhabitpage',
            name='importance',
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='carbon_footprint_impact',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='footnote',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Inspirational quote or funny facts to leave the user on high note and strongly encourage sharing/saving ', max_length=100),
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='headline',
            field=models.CharField(blank=True, help_text='Attractive one liner to trigger compulsive tap', max_length=50),
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='nudge_post_heros'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The nude body. This should be a short paragraph where the carbon reduction habits should be highlighted', max_length=500),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='source',
            field=models.CharField(blank=True, help_text='Original author or source. If website or article. Use link field but only the domain name here! ', max_length=120),
        ),
    ]
