# Generated by Django 2.2.5 on 2021-02-23 03:49

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0017_auto_20210223_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('typeOf', models.CharField(choices=[('headline', 'headline'), ('study', 'Study'), ('source', 'Source')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='greenhabitpage',
            name='reference',
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='study_link',
            field=models.URLField(blank=True, help_text='study link'),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This should be a short paragraph where the carbon reduction habits should be highlighted', max_length=1000),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='carbon_footprint_impact',
            field=models.CharField(choices=[('high', 'High co2e reduction'), ('medium', 'Medium co2e reduction'), ('low', 'Low co2e reduction')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='headline',
            field=models.CharField(blank=True, help_text='Attractive one-liner to trigger compulsive tap', max_length=50),
        ),
    ]
