# Generated by Django 2.2.5 on 2021-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0018_auto_20210223_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhabitpage',
            name='headline_link',
            field=models.URLField(blank=True, help_text='headline link'),
        ),
        migrations.AddField(
            model_name='greenhabitpage',
            name='link',
            field=models.URLField(blank=True, help_text='headline link'),
        ),
    ]
