# Generated by Django 2.2.5 on 2021-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0019_auto_20210223_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='link',
            field=models.URLField(blank=True, help_text='other link'),
        ),
    ]
