# Generated by Django 2.2.5 on 2021-02-24 03:44

from django.db import migrations, models
import greenhabits.models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0020_auto_20210223_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='headline_link',
            field=models.URLField(blank=True, help_text='headline link', validators=[greenhabits.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='link',
            field=models.URLField(blank=True, help_text='other link', validators=[greenhabits.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='greenhabitpage',
            name='study_link',
            field=models.URLField(blank=True, help_text='study link', validators=[greenhabits.models.validate_url]),
        ),
    ]
