# Generated by Django 2.2.6 on 2019-10-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='type',
            field=models.CharField(choices=[('law', 'Law'), ('essential', 'Essential'), ('habit', 'Habit')], max_length=20),
        ),
    ]
