# Generated by Django 2.2.6 on 2019-10-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0003_auto_20191006_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhabitpage',
            name='date',
        ),
    ]
