# Generated by Django 2.2.6 on 2019-10-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0004_remove_greenhabitpage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhabitpage',
            old_name='type',
            new_name='importance',
        ),
    ]
