# Generated by Django 2.2.6 on 2019-10-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0005_auto_20191013_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='importance',
            field=models.CharField(choices=[('law', 'Law'), ('essential', 'Essential'), ('habit', 'Habit')], default='habit', max_length=20),
        ),
    ]
