# Generated by Django 2.2.6 on 2019-10-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('greenhabits', '0007_privacyterms_termandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termandconditions',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PrivacyTerms',
        ),
        migrations.DeleteModel(
            name='TermAndConditions',
        ),
    ]
