# Generated by Django 2.2.6 on 2019-10-26 22:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0009_privacyterms_termandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyterms',
            name='body',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.RawHTMLBlock())]),
        ),
        migrations.AlterField(
            model_name='termandconditions',
            name='body',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
