# Generated by Django 2.2.6 on 2019-10-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0010_auto_20191026_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhabitpage',
            name='source',
            field=models.CharField(blank=True, help_text='Original author', max_length=120),
        ),
    ]
