# Generated by Django 2.2.5 on 2019-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhabits', '0012_auto_20191027_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhabitpage',
            name='summary',
            field=models.CharField(blank=True, help_text='Keep this short and impactful', max_length=180),
        ),
    ]
