# Generated by Django 2.2.5 on 2019-10-31 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('greenhabits', '0014_auto_20191028_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyTerms',
            new_name='StaticPage',
        ),
        migrations.DeleteModel(
            name='TermAndConditions',
        ),
    ]
